[project]
name = "implement-bookrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.1",
    "jinja2>=3.1.6",
    "pytest>=9.0.2",
    "pyyaml>=6.0.3",
]
